### ISSUE TITLE
Hide your secrets

### ISSUE THREAD

**Issue by gordonje** [maxkarnold/covid-19_twitter_bot#3]
https://github.com/maxkarnold/covid-19_twitter_bot/blob/718d312692de7dfe2e6ab8c97ebee076a72eafc9/scraper.py#L10-L13

Your API keys are exposed to the world right now. Anyone can grab these and start using them, for example, to tweet malicious stuff from the account to which these are linked.

We didn't cover this in detail during class, but typically you want to exclude secrets such as API keys, usernames and passwords from your source code. There are lots of ways to do this.

One tool that's worked well for me is [direnv](https://direnv.net/). Direnv works by looking for a specially named system file whenever you change directories. If found, it reads secrets from those files into your shell's environment variables where they can be accessed by any process running in that shell (including a Python script).

In case you want address this issue, here is a plan:

- [ ] Delete these keys in the Twitter Developer Console.
- [ ] Generate new ones and copy them down, but don't share them.
- [ ] [Install](https://direnv.net/docs/installation.html) direnv
- [ ] [Hook](https://direnv.net/docs/hook.html) it into your shell
- [ ] Create a `.envrc` file in your project's directory
- [ ] Add the new API keys to this file
- [ ] Add `.envrc` to your `.gitignore` file for this project
- [ ] Replace the hard-coded keys on the above lines with calls to get these values from your environment (e.g., `api_key = os.environ.get('API_KEY')`. Note that you also need to import the [`os`](https://docs.python.org/3/library/os.html) module into whichever script is accessing these environment variables.

**Comment by maxkarnold** [comment]
I wasn't able to exactly figure out "direnv". I instead pip installed dotenv and created a .env file for the API keys. I added it to .gitignore, so it should achieve the same result.
