### ISSUE TITLE
Dynamic dates

### ISSUE THREAD

**Issue by gordonje** [maxkarnold/covid-19_twitter_bot#4]
https://github.com/maxkarnold/covid-19_twitter_bot/blob/718d312692de7dfe2e6ab8c97ebee076a72eafc9/scraper.py#L48-L83

Currently, it seems like this script will calculate new cases and deaths only for May 16 and 17.

In order to calculate new cases and deaths for today (regardless of the date) you need make use of the Python's [`datetime` module](https://docs.python.org/3/library/datetime.html) or some third-party package that relies on it (e.g., [Arrow](https://arrow.readthedocs.io/en/latest/)).

Based on the lines you have commented out, you were on the right track. Note that `yesterday_date` is an instance of [`datetime.date`](https://docs.python.org/3/library/datetime.html#datetime.date). But to use this calculated value as a filter, you need it as a string that matches the date format in the csv file, which is [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601).

Here's how you get it: `yesterday_date.isoformat()`

**Comment by maxkarnold** [comment]
I had forgotten about uncommenting the date before. I fixed that and just passed str(yesterday_date) within the if statement. I think this worked fine, but hopefully won't have problems in the future.
